server:
	verbosity: 1
	num-threads: 1	
	interface: 0.0.0.0@5335
	prefer-ip6: no
	prefer-ip4: yes
	outgoing-range: 4096
	outgoing-port-permit: 32768
	msg-cache-size: 4m
	msg-cache-slabs: 4
	num-queries-per-thread: 4096   
	udp-connect: yes
	rrset-cache-size: 4m
	rrset-cache-slabs: 4
	cache-min-ttl: 0
	cache-max-ttl: 86400
	infra-cache-slabs: 4
	do-ip4: yes
	do-ip6: no
	do-udp: yes
	do-tcp: yes
	use-systemd: no
	do-daemonize: no														   
 access-control: 0.0.0.0/0 allow   
 chroot: ""    
 username: ""
	directory: "/usr/local/unbound/" 
 logfile: ""
	use-syslog: no
	log-time-ascii: yes    
	log-servfail: yes   
	pidfile: "/usr/local/unbound/unbound.d/unbound.pid"    
	hide-identity: yes
	hide-version: yes
	hide-trustanchor: yes
	harden-short-bufsize: yes
	harden-large-queries: yes
	harden-glue: yes
	harden-dnssec-stripped: yes
	harden-below-nxdomain: yes    
	harden-algo-downgrade: yes
	qname-minimisation: yes
	aggressive-nsec: yes
	use-caps-for-id: no
	private-address: 10.0.0.0/8
	private-address: 172.16.0.0/12
	private-address: 192.168.0.0/16
	private-address: 169.254.0.0/16
	private-address: fd00::/8
	private-address: fe80::/10
	private-address: ::ffff:0:0/96
	do-not-query-localhost: yes
	deny-any: yes
	rrset-roundrobin: yes
	minimal-responses: yes
	disable-dnssec-lame-check: no
	module-config: "validator iterator"    
 auto-trust-anchor-file: "/usr/local/unbound/iana.d/root.key"
	trust-anchor-signaling: yes
	root-key-sentinel: yes
	val-max-restart: 5
	val-clean-additional: yes
	val-permissive-mode: no
	ignore-cd-flag: no
	serve-expired: no
	val-log-level: 2
	zonemd-permissive-mode: no
	key-cache-size: 4m
	key-cache-slabs: 4
	neg-cache-size: 1m
	unblock-lan-zones: no
	insecure-lan-zones: yes
 so-sndbuf: 0
 so-rcvbuf: 0
python:
dynlib:
remote-control:
auth-zone:
	name: "."
	primary: 170.247.170.2        # b.root-servers.net
	primary: 192.33.4.12          # c.root-servers.net
	primary: 199.7.91.13          # d.root-servers.net
	primary: 192.5.5.241          # f.root-servers.net
	primary: 192.112.36.4         # g.root-servers.net
	primary: 193.0.14.129         # k.root-servers.net
	primary: 192.0.47.132         # xfr.cjr.dns.icann.org
	primary: 192.0.32.132         # xfr.lax.dns.icann.org
	primary: 2801:1b8:10::b       # b.root-servers.net
	primary: 2001:500:2::c        # c.root-servers.net
	primary: 2001:500:2d::d       # d.root-servers.net
	primary: 2001:500:2f::f       # f.root-servers.net
	primary: 2001:500:12::d0d     # g.root-servers.net
	primary: 2001:7fd::1          # k.root-servers.net
	primary: 2620:0:2830:202::132 # xfr.cjr.dns.icann.org
	primary: 2620:0:2d0:202::132  # xfr.lax.dns.icann.org
	fallback-enabled: yes
	for-downstream: no
	for-upstream: yes
	zonemd-check: yes
 zonemd-reject-absence: no
	zonefile: "/usr/local/unbound/iana.d/root.zone"										
#include-toplevel: "/usr/local/unbound/conf.d/*.conf"
#include-toplevel: "/usr/local/unbound/zones.d/*.conf"