#!/bin/sh

DISABLE_SET_PERMS=${DISABLE_SET_PERMS:-false}
UNBOUND_UID=${UNBOUND_UID:-1000}
UNBOUND_GID=${UNBOUND_GID:-1000}

unbound_root=/usr/local/unbound

disable_set_perms=$DISABLE_SET_PERMS
if $disable_set_perms; then
  command="exec"
else
  set_perms=0
  if [ $(id -u _unbound) -ne $UNBOUND_UID ]; then
    usermod -o -u $UNBOUND_UID _unbound
    set_perms=1
  fi
  if [ $(id -g _unbound) -ne $UNBOUND_GID ]; then
    groupmod -o -g $UNBOUND_GID _unbound
    set_perms=1
  fi
  if [ $set_perms -eq 1 ]; then
    chown -R $UNBOUND_UID:$UNBOUND_GID $unbound_root >/dev/null 2>&1
  fi
  command="exec su-exec $UNBOUND_UID:$UNBOUND_GID"
fi

$command $unbound_root/sbin/unbound.sh $disable_set_perms