name: CD Build Canary Distroless Unbound QUIC Docker Image

on:
  workflow_run:
    workflows: ["CD Build Canary Distroless Unbound Docker Image"]
    types:
      - completed
  workflow_dispatch:

permissions: {}

jobs:

  buildvars:
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    outputs:
      IMAGE_BUILD_DATE: ${{ steps.vars.outputs.IMAGE_BUILD_DATE }}
      UNBOUND_VERSION: ${{ steps.vars.outputs.UNBOUND_VERSION }}
      UNBOUND_SHA256: ${{ steps.vars.outputs.UNBOUND_SHA256 }}
      OPENSSL_QUIC_BUILDENV_VERSION: ${{ steps.vars.outputs.OPENSSL_QUIC_BUILDENV_VERSION }}
      OPENSSL_VERSION: ${{ steps.vars.outputs.OPENSSL_VERSION }}
      OPENSSL_SHA256: ${{ steps.vars.outputs.OPENSSL_SHA256 }}
      NGTCP2_VERSION: ${{ steps.vars.outputs.NGTCP2_VERSION }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176
        with:
          egress-policy: audit
          
      - name: Checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set buildvars
        id: vars
        run: |
          echo IMAGE_BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") >> $GITHUB_OUTPUT

          source buildvars
          echo UNBOUND_VERSION="$UNBOUND_VERSION" >> $GITHUB_OUTPUT
          echo UNBOUND_SHA256="$UNBOUND_SHA256" >> $GITHUB_OUTPUT

          OPENSSL_ENV=$(curl -s https://raw.githubusercontent.com/madnuttah/openssl-buildenv/master/buildvars)

          OPENSSL_VERSION=$(echo "$OPENSSL_ENV" | grep '^OPENSSL_VERSION=' | cut -d= -f2)
          SUBVERSION=$(echo "$OPENSSL_ENV" | grep '^SUBVERSION=' | cut -d= -f2)
          OPENSSL_SHA256=$(echo "$OPENSSL_ENV" | grep '^OPENSSL_SHA256=' | cut -d= -f2)
          NGTCP2_VERSION=$(echo "$OPENSSL_ENV" | grep '^NGTCP2_VERSION=' | cut -d= -f2)

          FINAL="${OPENSSL_VERSION}-${SUBVERSION}"

          echo OPENSSL_QUIC_BUILDENV_VERSION="$FINAL-quic" >> $GITHUB_OUTPUT
          echo OPENSSL_VERSION="$OPENSSL_VERSION" >> $GITHUB_OUTPUT
          echo OPENSSL_SHA256="$OPENSSL_SHA256" >> $GITHUB_OUTPUT
          echo NGTCP2_VERSION="$NGTCP2_VERSION" >> $GITHUB_OUTPUT

  build:
    needs: buildvars
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_SLUG: "madnuttah/unbound"
      GHCR_SLUG: "ghcr.io/madnuttah/unbound"
      UNBOUND_DOCKER_IMAGE_VERSION: "canary-quic"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176
        with:
          egress-policy: audit

      - name: Checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Login to Dockerhub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
            ${{ env.GHCR_SLUG }}
          tags: |
            type=raw,value=${{ env.UNBOUND_DOCKER_IMAGE_VERSION }}

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v6,linux/arm/v7,linux/ppc64le,linux/s390x,linux/riscv64
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            OPENSSL_QUIC_BUILDENV_VERSION=${{ needs.buildvars.outputs.OPENSSL_QUIC_BUILDENV_VERSION }}
            OPENSSL_VERSION=${{ needs.buildvars.outputs.OPENSSL_VERSION }}
            OPENSSL_SHA256=${{ needs.buildvars.outputs.OPENSSL_SHA256 }}
            UNBOUND_VERSION=${{ needs.buildvars.outputs.UNBOUND_VERSION }}
            UNBOUND_SHA256=${{ needs.buildvars.outputs.UNBOUND_SHA256 }}
            NGTCP2_VERSION=${{ needs.buildvars.outputs.NGTCP2_VERSION }}
            UNBOUND_DOCKER_IMAGE_VERSION=${{ env.UNBOUND_DOCKER_IMAGE_VERSION }}
            IMAGE_BUILD_DATE=${{ needs.buildvars.outputs.IMAGE_BUILD_DATE }}
          file: ./unbound/canary_quic.Dockerfile
          push: true
          sbom: true
          provenance: true

          cache-from: |
            type=registry,ref=madnuttah/unbound:buildcache-quic
            type=registry,ref=ghcr.io/madnuttah/unbound:buildcache-quic
          cache-to: |
            type=registry,ref=madnuttah/unbound:buildcache-quic,mode=max
            type=registry,ref=ghcr.io/madnuttah/unbound:buildcache-quic,mode=max

          tags: |
            ${{ env.DOCKERHUB_SLUG }}:canary-quic
            ${{ env.GHCR_SLUG }}:canary-quic

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        if: ${{ github.event_name != 'pull_request' }}
        with:
          image-ref: ${{ env.DOCKERHUB_SLUG }}:canary-quic
          exit-code: "1"
          ignore-unfixed: false
          scan-type: image
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          format: "table"

      - name: Docker Scout CVEs
        uses: docker/scout-action@cd72f264beff1cd72735de31148b9d3244a0234a
        if: ${{ github.event_name != 'pull_request' }}
        with:
          command: cves
          image: ${{ env.DOCKERHUB_SLUG }}:canary-quic
          only-fixed: true
          only-severities: critical,high
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exit-code: false
