name: CD GitHub Actions Security Analysis with zizmor

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            ghcr.io:443
            github.com:443
            pkg-containers.githubusercontent.com:443
          
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          clean: true
          ref: ${{ github.event.pull_request.head.sha || github.ref_name }}

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0


# name: CD GitHub Actions Security Analysis with zizmor

# on:
  # push:
    # branches: ["main"]
  # pull_request:
    # branches: ["**"]

# permissions:
  # actions: read
  # contents: read


# jobs:
  # zizmor:
    # name: Run zizmor
    # runs-on: ubuntu-latest
    # permissions:
      # security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
    # steps:
      # # - name: Checkout repository
        # # uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        # # with:
          # # persist-credentials: false
          # # token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Checkout
        # uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        # with:
          # fetch-depth: 0
          # clean: true
          # ref: ${{ github.event.pull_request.head.sha || github.ref_name }}

      # - name: Run zizmor 🌈
        # uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6