name: Lint GitHub Actions

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
        # uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        # with:
          # persist-credentials: false
          # token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
            token: ${{ github.token }}
            
      - name: actionlint
        uses: docker://rhysd/actionlint:1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667
        continue-on-error: false
        with:
          args: '-ignore "label \"ubuntu-24.04-riscv\" is unknown" -ignore "label \"ubuntu-26.04-riscv\" is unknown"'

#        with:
#          args: "-config-file .github/actionlint.yaml"
