name: OpenSSF Scorecard

on:
  schedule:
    - cron: "0 3 * * 1" # weekly Monday 03:00
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Run Scorecard
        uses: ossf/scorecard-action@dc50aa9510b46c811795eb24b2f1ba02a914e534 # v2.3.3
        with:
          results_file: results.sarif
          publish_results: true
